Feature/dev 9856
Espressive/cascara pull request #119
Opened 2020-11-25 23:50 UTC by CaffeinatedAllie

Added mockups for new components and replaced line graph with stacked bar chart, because of drill down on click issue.

2020-12-02 20:06 UTC, lordpixel requested changes
This looks awesome @CaffeinatedAllie!
I left some comments regarding some warnings in the console, this is great 🙌

2020-12-02 20:06 UTC, lordpixel commented on packages/cascara/src/ui/Dashboard/data/PieChannel.json
> +[
The fix on this file won't be enough as we have [another file](https://github.com/Espressive/cascara/blob/develop/packages/cascara/src/ui/Dashboard/data/Pie.json) that requires labels too. For that other file we can do:

```javascript
[
  {
    "id": "How do I reset my password",
    "label": "How do I reset my password",
    "value": 371
  },
  {
    "id": "I need a VPN Account",
    "label": "I need a VPN Account",
    "value": 152
  },
  {
    "id": "What are the holidays we have off",
    "label": "What are the holidays we have off",
    "value": 291
  },
  {
    "id": "How do I use the VPN",
    "label": "How do I use the VPN",
    "value": 269
  },
  {
    "id": "What is for lunch today",
    "label": "What is for lunch today",
    "value": 54
  },
  {
    "id": "I need to change my W2",
    "label": "I need to change my W2",
    "value": 10
  },
  {
    "id": "When is open enrollment",
    "label": "When is open enrollment",
    "value": 3
  }
]
```

2020-12-03 00:20 UTC, lordpixel approved these changes

2020-12-07 19:51 UTC, brianespinosa commented on packages/cascara/src/ui/Dashboard/data/PieChannel.json
> +[
@CaffeinatedAllie could we get these console warnings resolved that @lordpixel mentioned here? Then we can get this merged.

2020-12-08 18:32 UTC, lordpixel approved these changes

2020-12-08 19:08 UTC, merged