Feature/fds 116 - Set up onAction function for feature parity with Table
Espressive/cascara pull request #141
Opened 2021-02-05 04:51 UTC by lordpixel

Hi team,

This adds actions to Form, here's what was done:

- create Form-specific ActionEdit component
- create Table-specific ActionEdit component
- add actions support to From
- update Table to use its own ActionEdit
- update any export/import, test, fixture as required

## Unit tests
Unit tests will be added as part of FDS-30.

## ActionBar layout
As you may notice, the buttons appear at the left side. We need to talk about the layout we are going to support as well as the AST to declare it.

## New Component Checklist

- [x] Includes unit tests for _ALL_ required FDS use cases
- [ ] Does not mute any top level API props in React
- [ ] Includes an explanation for any changes to Jest snapshots (should be a PR tag automatically added if this happens)
- [ ] Component uses `React.forwardRef()` when a single DOM node is returned, _AND_ it makes React-sense to access that DOM node

2021-02-05 05:13 UTC, lordpixel commented
Vercel build is failing because now Table and Form import their own `ActionEdit` component, but such component is not available in MDX scope.

My guess is that we should only import Table's ActionEdit and leave Form's out.

2021-02-05 20:44 UTC, brianespinosa commented
> Vercel build is failing because now Table and Form import their own `ActionEdit` component, but such component is not available in MDX scope.

Interesting. Let me take a look at this. Maybe we will need to import and export those directly from the components they are used in. For instance in Form.js:

```
import ActionEdit from './modules/ActionEdit`;

// component stuff

export {ActionEdit}

export default Form
```

2021-02-12 18:02 UTC, brianespinosa requested changes
@lordpixel we have some conflicts here. Please resolve those and then @ me so I can come back and review and test. I think we can get this in today... and possibly get the docs ready to go to also include this in the next alpha. I think this can ship as part of a new minor version 0.3.0. 🥳

2021-02-12 21:16 UTC, lordpixel commented on packages/cascara/src/modules/DataText/DataText.js
> +  isSecure: pt.bool,
The prop has been removed, conflicts have been solved. Thank you @brianespinosa!

2021-02-12 21:59 UTC, brianespinosa approved these changes

2021-02-12 22:00 UTC, merged