chore(FDS-189):[Cascara]: Validate data-component usage on Cascara
Espressive/cascara pull request #343
Opened 2022-01-08 18:32 UTC by rociobaena

Validate `data-component` usage on Cascara components

 Add the identifiable `data-component="ComponentName"`  to our components in Cascara.
## PR Author Checklist

- [x] PR title adheres to [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#specification)
- [x] I have finished reviewing the contents of this PR for accuracy
- [ ] If needed, I have included a [Changeset](https://github.com/changesets/changesets) and it follows [Semantic Versioning principles](https://semver.org/)
- [ ] I have completed all of the above and have enabled `auto-merge` for this PR

2022-01-10 17:08 UTC, lordpixel approved these changes

2022-01-10 17:10 UTC, lordpixel commented
@rociobaena this looks good, we only need to update snapshots.

2022-01-10 23:24 UTC, lordpixel submitted a review, later dismissed

2022-01-11 18:20 UTC, brianespinosa commented on packages/cascara/src/ui/Columns/Columns.js
> +
I don't see anywhere else in the component where we are using the `componentName` const. To me this feels like extra work for something that we should not be considering a configurable global. This data attribute should always be the name of the component itself. I think we should just put these strings directly on the `data-component='Columns'` attribute.

2022-01-11 18:21 UTC, brianespinosa commented on packages/cascara/src/ui/List/List.js
> +      {...compositeState}
```suggestion
      {...compositeState}
      className={styles._}
```
Let's move this spread value above className

2022-01-11 18:23 UTC, brianespinosa requested changes
@rociobaena I am seeing that we are defining componentName as a const above the component and using that on the component below. Because are not using componentName anywhere else, this is extra abstraction that I do not think helps us right now. Let's go ahead and define this string directly on the data-component attribute.

2022-01-11 20:07 UTC, rociobaena commented
I close this PR due to a rename this branch to include a description, this includes the feedback provided here: https://github.com/Espressive/cascara/pull/345.

2022-01-11 20:07 UTC, closed without merging