feat(FDS-519): [Atoms] Add datepicker component
Espressive/cascara pull request #417
Opened 2022-03-24 20:18 UTC by rociobaena

Create date picker component
This component will be exported in @espressive/cascara
Fixture and documentation added.

Create date picker component
This component will be exported in @espressive/cascara
Fixture and documentation added.

## PR Author Checklist

- [ ] PR title adheres to [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#specification)
- [ ] I have finished reviewing the contents of this PR for accuracy
- [ ] If needed, I have included a [Changeset](https://github.com/changesets/changesets) and it follows [Semantic Versioning principles](https://semver.org/)
- [ ] I have completed all of the above and have enabled `auto-merge` for this PR

### Dependencies
Antd has been added

## PR Author Checklist

- [ ] PR title adheres to [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#specification)
- [ ] I have finished reviewing the contents of this PR for accuracy
- [ ] If needed, I have included a [Changeset](https://github.com/changesets/changesets) and it follows [Semantic Versioning principles](https://semver.org/)
- [ ] I have completed all of the above and have enabled `auto-merge` for this PR

2022-03-25 00:22 UTC, lordpixel requested changes
@rociobaena This needs to go to develop, instead of Main.

Also, the code is now frozen until  an upstream PR is merged into develop to close the release loop. Please allow me to run that process first.

2022-03-25 02:27 UTC, rociobaena commented
> @rociobaena This needs to go to develop, instead of Main.
> 
> Also, the code is now frozen until an upstream PR is merged into develop to close the release loop. Please allow me to run that process first.

Manu, sorry. I didn't notice the branch was main. Thank you for pointing out it. Target changed.

2022-03-29 17:38 UTC, lordpixel commented
@rociobaena this looks good, we only need to wait for the upstream PR to be merged.

2022-03-30 18:07 UTC, lordpixel requested changes
@rociobaena this looks OK, we are just missing the unit tests and I left a comment.

2022-03-30 18:07 UTC, lordpixel commented on packages/cascara/src/atoms/DatePicker/DatePicker.js
> +  /** String that will define the type of calendar to present date|week|month|quarter|year */
@rociobaena let's all `picker` possible values in a `_globals.js` file:

```javascript
const PICKER_TYPE = {
    DATE: 'DATE',
    WEEK: 'WEEK',
    MONTH: 'MONTH',
    QUARTER: 'QUARTER',
    YEAR: 'YEAR'
};

// so in props we can do this:
picker: oneOf(Object.keys(PICKER_TYPE),
```

2022-03-30 20:01 UTC, odiseo42 approved these changes

2022-03-30 20:10 UTC, lordpixel approved these changes
👍

2022-03-30 20:10 UTC, merged